# Generated by Django 4.0.4 on 2022-05-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meddata', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons'), ('Ophthalmologists', 'Ophthalmologists'), ('Orthopedic Surgeons', 'Orthopedic Surgeons'), ('Pediatricians', 'Pediatricians'), ('Neurologists', 'Neurologists'), ('Physciotherapists', 'Physciotherapists')], default='Cardiologist', max_length=50),
        ),
    ]
